kubernetes/apps/finesse-guidance/finesse-guidance-backend-deployment.yml
kubernetes/apps/finesse-guidance/finesse-guidance-frontend-deployment.yml
kubernetes/apps/finesse-guidance/finesse-guidance-ingress.yml
kubernetes/apps/finesse-guidance/finesse-guidance-namespace.yml
kubernetes/apps/finesse/finesse-backend-deployment.yml
kubernetes/apps/finesse/finesse-frontend-deployment.yml

Issue #42: Created new deployment for finesse-guidance

---

.yamllint.yml
kubernetes/aks/apps/demo/kustomization.yaml
kubernetes/aks/apps/finesse/kustomization.yaml
kubernetes/aks/system/argocd/kustomization.yaml
kubernetes/aks/system/cert-manager/kustomization.yaml
kubernetes/aks/system/cloudnativepg/argo-app.yaml
kubernetes/aks/system/cloudnativepg/base/cnpg-1.22.1.yaml
kubernetes/aks/system/cloudnativepg/kustomization.yaml
kubernetes/aks/system/external-dns/kustomization.yaml
kubernetes/aks/system/ingress-nginx/kustomization.yaml
kubernetes/aks/system/monitoring/kustomization.yaml
kubernetes/aks/system/vault/kustomization.yaml

- Closes #79 
Note: I also changed the .yamllint.yml file to match rules based on https://github.com/kubernetes-sigs/kubespray. A reliable source for Kubernetes YAML indentation management

issue #79: Deployed cloudnativepg

---

kubernetes/aks/apps/argo-apps/kustomization.yaml
kubernetes/aks/apps/nachet/argo-app.yaml
kubernetes/aks/apps/nachet/base/nachet-backend-deployment.yml
kubernetes/aks/apps/nachet/base/nachet-frontend-deployment.yml
kubernetes/aks/apps/nachet/base/nachet-ingress.yaml
kubernetes/aks/apps/nachet/base/nachet-namespace.yml
kubernetes/aks/apps/nachet/kustomization.yaml

issue #86: Created nachet deployment  + added the deployment to argo apps

---

kubernetes/aks/system/vault/helm/values.yaml

Setup and configure a dashboard for vault

---

kubernetes/aks/apps/nachet/base/nachet-ingress.yaml

Per's Amir's request. Increasing nachet proxy body size.

Issue #104: Increase proxy body size for uploading images to nachet

---

kubernetes/aks/system/ingress-nginx/helm/values.yaml

114 ingress client max body size

---

kubernetes/aks/apps/argo-apps/kustomization.yaml
kubernetes/aks/apps/bytebase/argo-app.yaml
kubernetes/aks/apps/bytebase/base/ingress.yaml
kubernetes/aks/apps/bytebase/base/postgres-deployment.yaml
kubernetes/aks/apps/bytebase/base/secrets.yaml
kubernetes/aks/apps/bytebase/helm/values.yaml
kubernetes/aks/apps/bytebase/kustomization.yaml

This deployment offers a first instance of bytebase to allow developers to test the platform in a real environment.
Configuration to do after deployment merged : 
- [configure SSO](https://www.bytebase.com/docs/administration/sso/overview/)
- [VCS integration with our organisation](https://www.bytebase.com/docs/vcs-integration/overview/)

Issue #121: Bytebase deployment

---

kubernetes/aks/apps/finesse/base/finesse-secrets.yaml

Issue #144: update `finesse-backend` envs to version 6

---

kubernetes/aks/system/argocd/helm/values.yaml

Added policies for nachet and finesse github role inside ArgoCD

---

.github/workflows/workflow.yml
kubernetes/aks/apps/argo-apps/kustomization.yaml

remove unused ingresses from Howard

---

kubernetes/aks/apps/nachet/base/nachet-backend-deployment.yml

- Change the image deployment of Nachet Backend from 51-implementing-2-models to the main branch

fixes #114: change image to nachet-backend main branch

---

.yamllint.yml
kubernetes/aks/apps/nachet/base/nachet-ingress.yaml

Adding authentication to nachet with Github as IdP

Issue #163: Add auth with vouch to nachet

---

kubernetes/aks/apps/nachet/base/nachet-secrets.yaml

issue #172: update Nachet secret version

---

kubernetes/aks/system/argocd/helm/values.yaml

Updated policies from ArgoCD to sync rbacs permissions with Github Data team for bytebase instance.

Issue #170: Update policies for argocd with data team

---

kubernetes/aks/apps/open-webui/base/webui-ingress.yaml

Issue #177: changed openwebui cname to assist

---

kubernetes/aks/apps/argo-apps/kustomization.yaml
kubernetes/aks/system/trivy/argo-app.yaml
kubernetes/aks/system/trivy/helm/values.yaml
kubernetes/aks/system/trivy/kustomization.yaml

Issue #145: Trivy operator helm chart

---

kubernetes/aks/system/falco/argo-app.yaml
kubernetes/aks/system/falco/helm/falco-exporter-values.yaml
kubernetes/aks/system/falco/helm/falco-values.yaml
kubernetes/aks/system/falco/helm/falcosidekick-values.yaml
kubernetes/aks/system/falco/kustomization.yaml

issue #147: falco, falcosidekick and falco-exporter configuration

---

kubernetes/aks/apps/open-webui/base/webui-ingress.yaml

issue #213: changed assist ingress to louis

---

kubernetes/aks/apps/argo-apps/kustomization.yaml
kubernetes/aks/apps/louis/argo-app.yaml
kubernetes/aks/apps/louis/base/backend/ollama-service.yaml
kubernetes/aks/apps/louis/base/backend/ollama-statefulset.yaml
kubernetes/aks/apps/louis/base/ui/webui-deployment.yaml
kubernetes/aks/apps/louis/base/ui/webui-ingress.yaml
kubernetes/aks/apps/louis/base/ui/webui-pvc.yaml
kubernetes/aks/apps/louis/base/ui/webui-service.yaml
kubernetes/aks/apps/louis/kustomization.yaml

issue #217: louis deployment

---

kubernetes/aks/apps/finesse/base/finesse-secrets.yaml

issue #225: update finesse-backend envs to version 9

---

cron-toggle-power-k8s-cluster.yaml

issue #235: created cron-toggle-power-k8s-cluster.yaml for azure devops

---

kubernetes/aks/apps/finesse/internal/secrets.yaml

issue #246: update secrets to version 3

---

README-fr.md
README.md
docs/en/adr/011-gitops.en-ca.md
docs/en/adr/012-secret-management.en-ca.md
docs/en/adr/013-IaC-tool.en-ca.md
docs/en/adr/016-networking.en-ca.md
docs/fr/adr/011-gitops.fr-ca.md
docs/fr/adr/012-secret-management.fr-ca.md
docs/fr/adr/013-IaC-tool.fr-ca.md
docs/fr/adr/016-networking.fr-ca.md
mkdocs-en.yml
mkdocs-fr.yml

- Closes #255 
For the doc migration see: https://github.com/ai-cfia/dev-rel-docs/pull/140

Issue #255: mermaid diagrams support

---

apply-terraform-dev.yml
apply-terraform-staging.yml
terraform/dev/main.tf
terraform/dev/providers.tf
terraform/dev/resources.tf
terraform/dev/variables.tf
terraform/modules/azure-key-vault/main.tf
terraform/modules/azure-key-vault/providers.tf
terraform/modules/azure-key-vault/variables.tf

issue #277: Creating the k8s cluster for the dev subscription

---

kubernetes/aks/apps/argo-apps/kustomization.yaml
kubernetes/aks/system/ingress-nginx/argo-app.yaml
terraform/dev/main.tf
terraform/modules/azure-kubernetes-cluster/main.tf
terraform/staging/main.tf
terraform/staging/providers.tf
terraform/staging/variables.tf

issue #284: remove the aks gpu cluster

---

kubernetes/aks/apps/argo-apps/kustomization.yaml
kubernetes/aks/apps/louis/argo-app.yaml
kubernetes/aks/apps/louis/base/litellm/deployment.yaml

issue #286: litellm deployment

---

kubernetes/aks/apps/louis/base/backend/ollama-deployment.yaml
kubernetes/aks/apps/louis/base/litellm/deployment.yaml
kubernetes/aks/apps/louis/base/ui/webui-deployment.yaml
kubernetes/aks/apps/nachet/base/nachet-backend-deployment.yml
kubernetes/aks/apps/nachet/base/nachet-frontend-deployment.yml

Nachet and louis deployment update (securityContext, PDB, etc..)

---

kubernetes/aks/apps/ailab/base/deployment.yaml
kubernetes/aks/apps/fertiscan/base/fertiscan-backend-deployment.yaml
kubernetes/aks/apps/fertiscan/base/fertiscan-frontend-deployment.yaml
kubernetes/aks/apps/finesse/internal/finesse-backend-deployment.yml
kubernetes/aks/apps/finesse/internal/finesse-frontend-deployment.yml
kubernetes/aks/apps/finesse/public/finesse-backend-deployment.yml
kubernetes/aks/apps/finesse/public/finesse-frontend-deployment.yml
kubernetes/aks/apps/librechat/base/librechat-deployment.yaml
kubernetes/aks/apps/librechat/base/millisearch-deployment.yaml
kubernetes/aks/apps/librechat/base/mongo-deployment.yaml
kubernetes/aks/apps/librechat/base/pgvector-deployment.yaml
kubernetes/aks/apps/librechat/base/rag-api-deployment.yaml
kubernetes/aks/apps/louis/base/backend/ollama-deployment.yaml
kubernetes/aks/apps/louis/base/litellm/deployment.yaml
kubernetes/aks/apps/louis/base/ui/webui-deployment.yaml
kubernetes/aks/apps/nachet/base/nachet-backend-deployment.yml
kubernetes/aks/apps/nachet/base/nachet-frontend-deployment.yml

- Closes #319 
- Also added, `revisionHistoryLimit` to nachet, louis, librechat, finesse, fertiscan

Anti-affinity and node affinity

---

docs/en/workflow.md
docs/en/workflow/create-release-pr-labelling.md
docs/fr/workflow.md
docs/fr/workflow/create-release-pr-labelling.md
mkdocs-en.yml
mkdocs-fr.yml

issue #322: create release and pr labelling workflow documentation

---

kubernetes/aks/apps/argo-apps/kustomization.yaml
kubernetes/aks/apps/webtop/argo-app.yaml
kubernetes/aks/apps/webtop/base/webtop-deployment.yaml
kubernetes/aks/apps/webtop/base/webtop-ingress.yaml
kubernetes/aks/apps/webtop/base/webtop-secrets.yaml
kubernetes/aks/apps/webtop/kustomization.yaml

issue #309: docker-webtop deployment

---

docs/en/configuration.md
kubernetes/aks/apps/fertiscan/base/fertiscan-backend-deployment.yaml
kubernetes/aks/apps/fertiscan/base/fertiscan-frontend-deployment.yaml
kubernetes/aks/apps/nachet/base/nachet-backend-deployment.yml
kubernetes/aks/apps/nachet/base/nachet-frontend-deployment.yml

Issue #327: Update security context to fix out of syncs warnings on argocd

---

kubernetes/aks/system/monitoring/helm/loki-stack-values.yaml

Issue #329: address loki insuficient disk space

---

kubernetes/aks/apps/fertiscan/base/fertiscan-secrets.yaml

Update fertiscan backend's secrets

---

kubernetes/aks/apps/fertiscan/base/fertiscan-backend-deployment.yaml

ref: https://github.com/ai-cfia/howard/issues/335

Issue #335: Update fertiscan-backend to fix-docs branch changes

---

kubernetes/aks/apps/fertiscan/base/fertiscan-backend-deployment.yaml
kubernetes/aks/apps/fertiscan/base/fertiscan-secrets.yaml

ref https://github.com/ai-cfia/howard/issues/337

Update fertiscan secret key name, secret version and backend image tag

---

kubernetes/aks/apps/fertiscan/base/fertiscan-ingress.yaml

Issue #339: add ingress for backend

---

kubernetes/aks/apps/fertiscan/base/fertiscan-backend-deployment.yaml

Issue #342: Update fertiscan-backend image tag

---

kubernetes/aks/apps/ailab/prod/ailab-ingress.yaml
kubernetes/aks/apps/argo-apps/kustomization.yaml
kubernetes/aks/apps/fertiscan/base/fertiscan-ingress.yaml
kubernetes/aks/apps/finesse/internal/ingress.yaml
kubernetes/aks/apps/louis/base/ui/webui-ingress.yaml
kubernetes/aks/apps/nachet/base/nachet-ingress.yaml
kubernetes/aks/apps/webtop/base/webtop-ingress.yaml
kubernetes/aks/system/gatus/argo-app.yaml
kubernetes/aks/system/gatus/base/configmap.yaml
kubernetes/aks/system/gatus/base/deployment.yaml
kubernetes/aks/system/gatus/base/ingress.yaml
kubernetes/aks/system/gatus/base/pvc.yaml
kubernetes/aks/system/gatus/base/serviceaccount.yaml
kubernetes/aks/system/gatus/kustomization.yaml
kubernetes/aks/system/monitoring/helm/alloy-values.yaml
kubernetes/aks/system/vault/base/ingress.yml

Issue #344: Gatus deployment

---

.github/workflows/create-release.yml
.github/workflows/workflow.yml

Add pr labelling workflow

---

kubernetes/aks/apps/fertiscan/base/fertiscan-backend-deployment.yaml

Point to the latest image fertiscan-backend
Close #351

Issue #351: Update fertiscan-backend

---

kubernetes/aks/apps/fertiscan/base/fertiscan-backend-deployment.yaml

fix: update fertiscan-backend build

---

kubernetes/aks/apps/fertiscan/base/fertiscan-backend-deployment.yaml

fix: change fertiscan-backend image

---

terraform/modules/azure-kubernetes-cluster/backup.tf
terraform/modules/azure-kubernetes-cluster/variables.tf
terraform/staging/main.tf
terraform/staging/variables.tf

issue #348: aks backup configuration

---

.gitignore
kubernetes/aks/apps/fertiscan/base/fertiscan-frontend-deployment.yaml

issue #361: point fertiscan-frontend image to 233-use-put-inspections

---

kubernetes/aks/apps/fertiscan/base/fertiscan-secrets.yaml

issue #363: update secret version

---

kubernetes/aks/apps/argo-apps/kustomization.yaml
kubernetes/aks/system/gh-runner/argo-app.yaml
kubernetes/aks/system/gh-runner/base/secrets.yaml
kubernetes/aks/system/gh-runner/helm/values.yaml
kubernetes/aks/system/gh-runner/kustomization.yaml

issue #365: gh runner configuration

---

.github/workflows/workflow.yml
Dockerfile
kubernetes/aks/apps/argo-apps/kustomization.yaml
kubernetes/aks/apps/test-app/argo-app.yaml
kubernetes/aks/apps/test-app/base/deployment.yaml
kubernetes/aks/apps/test-app/base/ingress.yaml
kubernetes/aks/apps/test-app/kustomization.yaml
test_app/main.py
test_app/requirements.txt

issue #369: test application

---

kubernetes/aks/apps/fertiscan/base/fertiscan-frontend-deployment.yaml

issue #381: point fertiscan-frontend on pr #247

---

kubernetes/aks/system/monitoring/helm/loki-stack-values.yaml

issue #371: loki ruler

---

kubernetes/aks/apps/fertiscan/base/fertiscan-frontend-deployment.yaml

issue #387: point fertiscan frontend on #251

---

kubernetes/aks/apps/argo-apps/kustomization.yaml
kubernetes/aks/apps/demo/auto/argo-app.yaml
kubernetes/aks/apps/demo/auto/base/deployment.yml
kubernetes/aks/apps/demo/auto/kustomization.yaml
kubernetes/aks/system/monitoring/argo-app-otel-operator.yaml
kubernetes/aks/system/monitoring/base/instrumentation.yaml
kubernetes/aks/system/monitoring/helm/otel-operator-values.yaml

Issue #394: Otel operator deployment and otel-auto demo app deployment

---

kubernetes/aks/apps/fertiscan/base/fertiscan-backend-deployment.yaml
kubernetes/aks/apps/fertiscan/base/instrumentation.yaml

Issue #396: Adds instrumentation for fertiscan

---

kubernetes/aks/apps/fertiscan/base/fertiscan-frontend-deployment.yaml

issue #400: point fertiscan frontend image to v1.0.0

---

terraform/modules/azure-postgresql-server/main.tf
terraform/modules/azure-postgresql-server/providers.tf
terraform/modules/azure-postgresql-server/variables.tf
terraform/staging/main.tf
terraform/staging/variables.tf

issue #405: fertiscan postgresql database server

---

kubernetes/aks/apps/fertiscan/base/fertiscan-backend-deployment.yaml
kubernetes/aks/apps/fertiscan/base/fertiscan-ingress.yaml

Issue #410

---

kubernetes/aks/apps/fertiscan-preview/base/fertiscan-secrets.yaml

issue #422: update fertiscan backend preview secrets version to 26

---

kubernetes/aks/apps/argo-apps/kustomization.yaml
kubernetes/aks/apps/vikunja/argo-app.yaml
kubernetes/aks/apps/vikunja/helm/values.yaml
kubernetes/aks/apps/vikunja/kustomization.yaml

closes #425 
Please note that the current deployment doesn't take care of secrets for database since the deployment is for experimental use and not yet fully accepted.

Issue #425: test vikunja as potential snippet tracking app

---

kubernetes/aks/apps/fertiscan/base/fertiscan-backend-deployment.yaml
kubernetes/aks/apps/fertiscan/base/fertiscan-secrets.yaml

Issue #459: Udpate with latest tag and new envs var

---

kubernetes/aks/apps/nachet/base/nachet-backend-deployment.yml
kubernetes/aks/apps/nachet/base/nachet-frontend-deployment.yml
kubernetes/aks/apps/nachet/base/nachet-ingress.yaml
kubernetes/aks/apps/nachet/base/nachet-rcnn-model-deployment.yaml
kubernetes/aks/apps/nachet/base/nachet-secrets.yaml

462 deploy nachet autologin

---

kubernetes/aks/apps/nachet/base/nachet-backend-deployment.yml

487 deploy nachet 138

---

kubernetes/aks/apps/nachet/base/nachet-swin-22-spp-model-deployment.yaml

SWIN 22 spp model

---

kubernetes/aks/apps/librechat/base/librechat-deployment.yaml
kubernetes/aks/apps/librechat/base/rag-api-deployment.yaml

closes #497 
Update librechat secrets

Issue 497 update librechat secrets

---

kubernetes/aks/apps/nachet/base/service-schedule.yaml

503 Nachet scaling schedule

---

docs/en/workflow.md
docs/en/workflow/create-release-pr-labelling.md
docs/en/workflow/github-metrics.md
docs/en/workflow/secrets.md
docs/fr/workflow.md
docs/fr/workflow/create-release-pr-labelling.md
docs/fr/workflow/github-metrics.md
docs/fr/workflow/secrets.md

- Closes #501 
- Closes #500 
- Closes #499

Gh workflow documentation

---

kubernetes/aks/apps/fertiscan-preview/base/fertiscan-blob-storage-mock.yml
kubernetes/aks/apps/nachet/base/nachet-backend-deployment.yml
kubernetes/aks/apps/nachet/base/nachet-blob-storage-mock.yml
kubernetes/aks/apps/nachet/base/nachet-frontend-deployment.yml
kubernetes/aks/apps/nachet/base/nachet-rcnn-model-deployment.yaml
kubernetes/aks/apps/nachet/base/nachet-swin-22-spp-model-deployment.yaml
kubernetes/aks/apps/nachet/base/nachet-swin-model-deployment.yaml

Issue 506 Azurite deployment

---

kubernetes/aks/apps/fertiscan-preview/base/fertiscan-blob-storage-mock.yml
kubernetes/aks/apps/nachet/base/nachet-backend-deployment.yml
kubernetes/aks/apps/nachet/base/nachet-blob-storage-mock.yml
kubernetes/aks/apps/nachet/base/nachet-frontend-deployment.yml
kubernetes/aks/apps/nachet/base/nachet-rcnn-model-deployment.yaml
kubernetes/aks/apps/nachet/base/nachet-swin-22-spp-model-deployment.yaml
kubernetes/aks/apps/nachet/base/nachet-swin-model-deployment.yaml
kubernetes/aks/apps/nachet/base/service-schedule.yaml

506 Redeploy Azurite ramdisk workspace

---

.github/workflows/workflow.yml
terraform/modules/azure-default-iam/providers.tf
terraform/modules/azure-storage-account/variables.tf
terraform/staging/variables.tf

issue #512: added check-commit-author workflow

---

kubernetes/aks/apps/nachet/base/nachet-backend-deployment.yml
kubernetes/aks/apps/nachet/base/nachet-swin-27-spp-model-deployment.yaml

542 deploy 27spp nachet

---

kubernetes/aks/apps/nachet/base/nachet-backend-deployment.yml

Issue 544 update nachet backend datastore

---

kubernetes/aks/apps/nachet/base/nachet-backend-deployment.yml

Issue 546 Debug Nachet Datastore

---

kubernetes/aks/apps/nachet/base/nachet-backend-deployment.yml

Issue 548 update nachet backend image pull policy

---

kubernetes/aks/apps/nachet/base/nachet-swin-27-spp-model-deployment.yaml

Issue 551 increase nachet 27spp model resource alloc

---

kubernetes/aks/apps/argo-apps/kustomization.yaml

Issue 553 undeploy unused apps
